package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acceso generated by hbm2java
 */
@Entity
@Table(name="ACCESO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Acceso  implements java.io.Serializable {


     private AccesoId id;
     private Menu menu;
     private Usuario usuario;
     private String vistas;

    public Acceso() {
    }

	
    public Acceso(AccesoId id, Menu menu, Usuario usuario) {
        this.id = id;
        this.menu = menu;
        this.usuario = usuario;
    }
    public Acceso(AccesoId id, Menu menu, Usuario usuario, String vistas) {
       this.id = id;
       this.menu = menu;
       this.usuario = usuario;
       this.vistas = vistas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUsuario", column=@Column(name="ID_USUARIO", nullable=false, length=15) ), 
        @AttributeOverride(name="idMenu", column=@Column(name="ID_MENU", nullable=false) ) } )
    public AccesoId getId() {
        return this.id;
    }
    
    public void setId(AccesoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MENU", nullable=false, insertable=false, updatable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="VISTAS", length=50)
    public String getVistas() {
        return this.vistas;
    }
    
    public void setVistas(String vistas) {
        this.vistas = vistas;
    }




}


