package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccesoId generated by hbm2java
 */
@Embeddable
public class AccesoId implements java.io.Serializable {

    private String idRol;
    private String idMenu;

    public AccesoId() {
    }

    public AccesoId(String idRol, String idMenu) {
        this.idRol = idRol;
        this.idMenu = idMenu;
    }

    @Column(name = "ID_ROL", nullable = false)
    public String getIdRol() {
        return this.idRol;
    }

    public void setIdRol(String idRol) {
        this.idRol = idRol;
    }

    @Column(name = "ID_MENU", nullable = false)
    public String getIdMenu() {
        return this.idMenu;
    }

    public void setIdMenu(String idMenu) {
        this.idMenu = idMenu;
    }

}
