package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Afiliacion generated by hbm2java
 */
@Entity
@Table(name="AFILIACION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Afiliacion  implements java.io.Serializable {


     private String idTrabajador;
     private int idRpensionario;
     private String observacion;
     private String nrocuspp;

    public Afiliacion() {
    }

	
    public Afiliacion(String idTrabajador, int idRpensionario) {
        this.idTrabajador = idTrabajador;
        this.idRpensionario = idRpensionario;
    }
    public Afiliacion(String idTrabajador, int idRpensionario, String observacion, String nrocuspp) {
       this.idTrabajador = idTrabajador;
       this.idRpensionario = idRpensionario;
       this.observacion = observacion;
       this.nrocuspp = nrocuspp;
    }
   
     @Id 

    
    @Column(name="ID_TRABAJADOR", unique=true, nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    
    @Column(name="ID_RPENSIONARIO", nullable=false)
    public int getIdRpensionario() {
        return this.idRpensionario;
    }
    
    public void setIdRpensionario(int idRpensionario) {
        this.idRpensionario = idRpensionario;
    }

    
    @Column(name="OBSERVACION", length=50)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="NROCUSPP", length=25)
    public String getNrocuspp() {
        return this.nrocuspp;
    }
    
    public void setNrocuspp(String nrocuspp) {
        this.nrocuspp = nrocuspp;
    }




}


