package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AfiliacionId generated by hbm2java
 */
@Embeddable
public class AfiliacionId  implements java.io.Serializable {


     private String idTrabajador;
     private int idRpensionario;

    public AfiliacionId() {
    }

    public AfiliacionId(String idTrabajador, int idRpensionario) {
       this.idTrabajador = idTrabajador;
       this.idRpensionario = idRpensionario;
    }
   


    @Column(name="ID_TRABAJADOR", nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }


    @Column(name="ID_RPENSIONARIO", nullable=false)
    public int getIdRpensionario() {
        return this.idRpensionario;
    }
    
    public void setIdRpensionario(int idRpensionario) {
        this.idRpensionario = idRpensionario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AfiliacionId) ) return false;
		 AfiliacionId castOther = ( AfiliacionId ) other; 
         
		 return ( (this.getIdTrabajador()==castOther.getIdTrabajador()) || ( this.getIdTrabajador()!=null && castOther.getIdTrabajador()!=null && this.getIdTrabajador().equals(castOther.getIdTrabajador()) ) )
 && (this.getIdRpensionario()==castOther.getIdRpensionario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTrabajador() == null ? 0 : this.getIdTrabajador().hashCode() );
         result = 37 * result + this.getIdRpensionario();
         return result;
   }   


}


