package com.bruce.dao.to;
// Generated 06/08/2018 11:27:43 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Afiliacion generated by hbm2java
 */
@Entity
@Table(name = "AFILIACION",
        schema = "dbo",
        catalog = "BDBRUCE"
)
public class Afiliacion implements java.io.Serializable {

    private String idTrabajador;
    private RegimenPensionario regimenPensionario;
    private Trabajador trabajador;
    private String observacion;
    private String nrocuspp;

    public Afiliacion() {
    }

    public Afiliacion(RegimenPensionario regimenPensionario, Trabajador trabajador) {
        this.regimenPensionario = regimenPensionario;
        this.trabajador = trabajador;
    }

    public Afiliacion(RegimenPensionario regimenPensionario, Trabajador trabajador, String observacion, String nrocuspp) {
        this.regimenPensionario = regimenPensionario;
        this.trabajador = trabajador;
        this.observacion = observacion;
        this.nrocuspp = nrocuspp;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "trabajador"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID_TRABAJADOR", unique = true, nullable = false, length = 15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @JsonManagedReference
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_RPENSIONARIO", nullable = false)
    public RegimenPensionario getRegimenPensionario() {
        return this.regimenPensionario;
    }

    public void setRegimenPensionario(RegimenPensionario regimenPensionario) {
        this.regimenPensionario = regimenPensionario;
    }

    @JsonBackReference
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Trabajador getTrabajador() {
        return this.trabajador;
    }

    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Column(name = "OBSERVACION", length = 50)
    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Column(name = "NROCUSPP", length = 25)
    public String getNrocuspp() {
        return this.nrocuspp;
    }

    public void setNrocuspp(String nrocuspp) {
        this.nrocuspp = nrocuspp;
    }

}
