package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AlmuerzoTrabajador generated by hbm2java
 */
@Entity
@Table(name="ALMUERZO_TRABAJADOR"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class AlmuerzoTrabajador  implements java.io.Serializable {


     private AlmuerzoTrabajadorId id;
     private String estado;

    public AlmuerzoTrabajador() {
    }

    public AlmuerzoTrabajador(AlmuerzoTrabajadorId id, String estado) {
       this.id = id;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="fecha", column=@Column(name="FECHA", nullable=false, length=10) ) } )
    public AlmuerzoTrabajadorId getId() {
        return this.id;
    }
    
    public void setId(AlmuerzoTrabajadorId id) {
        this.id = id;
    }

    
    @Column(name="ESTADO", nullable=false, length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


