package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "AREA",
        schema = "dbo",
        catalog = "BDBRUCE"
)
public class Area implements java.io.Serializable {

    private String idArea;
    private String nombre;
    private String descripcion;
    private boolean situacion;
    private String idSuparea;
    private boolean leaf;
    
    private String parentId;
    private String lastParentId;

    public Area() {
    }

    public Area(String idArea, String nombre, boolean situacion, String idSuparea) {
        this.idArea = idArea;
        this.nombre = nombre;
        this.situacion = situacion;
        this.idSuparea = idSuparea;
    }

    @Id
    @Column(name = "ID_AREA", unique = true, nullable = false)
    public String getIdArea() {
        return this.idArea;
    }

    public void setIdArea(String idArea) {
        this.idArea = idArea;
    }

    @Column(name = "NOMBRE", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION")
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    @Column(name = "ID_SUPAREA")
    public String getIdSuparea() {
        return idSuparea;
    }

    public void setIdSuparea(String idSuparea) {
        this.idSuparea = idSuparea;
    }

    @Column(name = "LEAF", nullable = false)
    public boolean isLeaf() {
        return leaf;
    }

    public void setLeaf(boolean leaf) {
        this.leaf = leaf;
    }
    
    @Transient
    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    
    @Transient
    public String getLastParentId() {
        return lastParentId;
    }

    public void setLastParentId(String lastParentId) {
        this.lastParentId = lastParentId;
    }
}
