package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "AREA",
         schema = "dbo",
         catalog = "BDBRUCE"
)
public class Area implements java.io.Serializable {

    private int idArea;
    private String nombre;
    private boolean situacion;
    private int idSuparea;

    private String mtype;
    private String parentId;

    public Area() {
    }

    public Area(int idArea, String nombre, boolean situacion, int idSuparea) {
        this.idArea = idArea;
        this.nombre = nombre;
        this.situacion = situacion;
        this.idSuparea = idSuparea;
    }

    @Id
    @Column(name = "ID_AREA", unique = true, nullable = false)
    public int getIdArea() {
        return this.idArea;
    }

    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }

    @Column(name = "NOMBRE", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    @Column(name = "ID_SUPAREA", nullable = false)
    public int getIdSuparea() {
        return idSuparea;
    }

    public void setIdSuparea(int idSuparea) {
        this.idSuparea = idSuparea;
    }

    @Transient
    public String getMtype() {
        return String.valueOf(this.idArea);
    }

    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    @Transient
    public String getParentId() {
        return String.valueOf(this.idSuparea);
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
}
