package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="AREA"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Area  implements java.io.Serializable {


     private int idArea;
     private String nombre;
     private boolean situacion;
     private Set<Subarea> subareas = new HashSet<Subarea>(0);

    public Area() {
    }

	
    public Area(int idArea, String nombre, boolean situacion) {
        this.idArea = idArea;
        this.nombre = nombre;
        this.situacion = situacion;
    }
    public Area(int idArea, String nombre, boolean situacion, Set<Subarea> subareas) {
       this.idArea = idArea;
       this.nombre = nombre;
       this.situacion = situacion;
       this.subareas = subareas;
    }
   
     @Id 

    
    @Column(name="ID_AREA", unique=true, nullable=false)
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }

    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<Subarea> getSubareas() {
        return this.subareas;
    }
    
    public void setSubareas(Set<Subarea> subareas) {
        this.subareas = subareas;
    }




}


