package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;

/**
 * AsistenciaId generated by hbm2java
 */
public class AsistenciaId implements java.io.Serializable {

    private String idTrabajador;
    private String idAsistencia;

    public AsistenciaId() {
    }

    public AsistenciaId(String idTrabajador, String idAsistencia) {
        this.idTrabajador = idTrabajador;
        this.idAsistencia = idAsistencia;
    }

    @Column(name = "ID_TRABAJADOR", nullable = false)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Column(name = "ID_ASISTENCIA", nullable = false)
    public String getIdAsistencia() {
        return idAsistencia;
    }

    public void setIdAsistencia(String idAsistencia) {
        this.idAsistencia = idAsistencia;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + Objects.hashCode(this.idTrabajador);
        hash = 19 * hash + Objects.hashCode(this.idAsistencia);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AsistenciaId other = (AsistenciaId) obj;
        if (!Objects.equals(this.idTrabajador, other.idTrabajador)) {
            return false;
        }
        if (!Objects.equals(this.idAsistencia, other.idAsistencia)) {
            return false;
        }
        return true;
    }

}
