package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "ASISTENCIA", schema = "dbo", catalog = "BDBRUCE")
@IdClass(value = AsistenciaId.class)
public class Asistencia implements java.io.Serializable {

    private String idTrabajador;
    private String idAsistencia;
    private Date fecha;
    private String hmarca;
    
    private String fechaTemp;

    private String trabajador;

    public Asistencia() {
    }

    public Asistencia(String idTrabajador, Date fecha, String hmarca, String trabajador) {
        this.idTrabajador = idTrabajador;
        this.fecha = fecha;
        this.hmarca = hmarca;
        this.trabajador = trabajador;
    }

    public Asistencia(String idTrabajador, String idAsistencia, Date fecha, String hmarca) {
        this.idTrabajador = idTrabajador;
        this.idAsistencia = idAsistencia;
        this.fecha = fecha;
        this.hmarca = hmarca;
    }

    @Id
    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Id
    @Column(name = "ID_ASISTENCIA", nullable = false, length = 8)
    public String getIdAsistencia() {
        return idAsistencia;
    }

    public void setIdAsistencia(String idAsistencia) {
        this.idAsistencia = idAsistencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA", nullable = false, length = 10)
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Transient
    public String getFechaTemp() {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatoFecha.format(this.fecha);
    }

    public void setFechaTemp(String fechaTemp) {
        this.fechaTemp = fechaTemp;
    }

    @Column(name = "HMARCA", nullable = false, length = 10)
    public String getHmarca() {
        return hmarca;
    }

    public void setHmarca(String hmarca) {
        this.hmarca = hmarca;
    }

    @Transient
    public String getTrabajador() {
        return trabajador;
    }

    public void setTrabajador(String trabajador) {
        this.trabajador = trabajador;
    }

}
