package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CargoContrato generated by hbm2java
 */
@Entity
@Table(name="CARGO_CONTRATO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class CargoContrato  implements java.io.Serializable {


     private CargoContratoId id;
     private Date fecha;
     private String observacion;
     private int idCargo;

    public CargoContrato() {
    }

	
    public CargoContrato(CargoContratoId id, Date fecha, int idCargo) {
        this.id = id;
        this.fecha = fecha;
        this.idCargo = idCargo;
    }
    public CargoContrato(CargoContratoId id, Date fecha, String observacion, int idCargo) {
       this.id = id;
       this.fecha = fecha;
       this.observacion = observacion;
       this.idCargo = idCargo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idContrato", column=@Column(name="ID_CONTRATO", nullable=false) ), 
        @AttributeOverride(name="idCcontrato", column=@Column(name="ID_CCONTRATO", nullable=false) ) } )
    public CargoContratoId getId() {
        return this.id;
    }
    
    public void setId(CargoContratoId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="OBSERVACION", length=100)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="ID_CARGO", nullable=false)
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }




}


