package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="CARGO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Cargo  implements java.io.Serializable {


     private int idCargo;
     private Date fecha;
     private String descripcion;
     private boolean situacion;
     private int idSubarea;

    public Cargo() {
    }

    public Cargo(int idCargo, Date fecha, String descripcion, boolean situacion, int idSubarea) {
       this.idCargo = idCargo;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.idSubarea = idSubarea;
    }
   
     @Id 

    
    @Column(name="ID_CARGO", unique=true, nullable=false)
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    
    @Column(name="ID_SUBAREA", nullable=false)
    public int getIdSubarea() {
        return this.idSubarea;
    }
    
    public void setIdSubarea(int idSubarea) {
        this.idSubarea = idSubarea;
    }




}


