package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "CARGO",
         schema = "dbo",
         catalog = "BDBRUCE"
)
public class Cargo implements java.io.Serializable {

    private int idCargo;
    private Subarea subarea;
    private Date fecha;
    private String descripcion;
    private boolean situacion;
    private Set<Funcion> funcions = new HashSet<Funcion>(0);
    private Set<CargoContrato> cargoContratos = new HashSet<CargoContrato>(0);

    public Cargo() {
    }

    public Cargo(int idCargo, Subarea subarea, Date fecha, String descripcion, boolean situacion) {
        this.idCargo = idCargo;
        this.subarea = subarea;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }

    public Cargo(int idCargo, Subarea subarea, Date fecha, String descripcion, boolean situacion, Set<Funcion> funcions, Set<CargoContrato> cargoContratos) {
        this.idCargo = idCargo;
        this.subarea = subarea;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.situacion = situacion;
        this.funcions = funcions;
        this.cargoContratos = cargoContratos;
    }

    @Id

    @Column(name = "ID_CARGO", unique = true, nullable = false)
    public int getIdCargo() {
        return this.idCargo;
    }

    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }

    @JsonManagedReference
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SUBAREA", nullable = false)
    public Subarea getSubarea() {
        return this.subarea;
    }

    public void setSubarea(Subarea subarea) {
        this.subarea = subarea;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA", nullable = false, length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
    public Set<Funcion> getFuncions() {
        return this.funcions;
    }

    public void setFuncions(Set<Funcion> funcions) {
        this.funcions = funcions;
    }

    @JsonBackReference
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
    public Set<CargoContrato> getCargoContratos() {
        return this.cargoContratos;
    }

    public void setCargoContratos(Set<CargoContrato> cargoContratos) {
        this.cargoContratos = cargoContratos;
    }

}
