package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "CARGO", schema = "dbo", catalog = "BDBRUCE" )
@IdClass(value = CargoId.class)
public class Cargo implements java.io.Serializable {

    private String idArea;
    private String idCargo;
    private String nombre;
    private String descripcion;
    private boolean situacion;

    public Cargo() {
    }

    public Cargo(String idArea, String idCargo, String nombre, String descripcion, boolean situacion) {
        this.idArea = idArea;
        this.idCargo = idCargo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }

    @Id
    @Column(name = "ID_AREA", nullable = false, length = 5)
    public String getIdArea() {
        return idArea;
    }

    public void setIdArea(String idArea) {
        this.idArea = idArea;
    }

    @Id
    @Column(name = "ID_CARGO", nullable = false)
    public String getIdCargo() {
        return this.idCargo;
    }

    public void setIdCargo(String idCargo) {
        this.idCargo = idCargo;
    }

    @Column(name = "NOMBRE", nullable = false, length = 60)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 150)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }
}
