package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoriaOcupacional generated by hbm2java
 */
@Entity
@Table(name="CATEGORIA_OCUPACIONAL"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class CategoriaOcupacional  implements java.io.Serializable {


     private String idCocupacional;
     private String descripcion;
     private boolean situacion;

    public CategoriaOcupacional() {
    }

    public CategoriaOcupacional(String idCocupacional, String descripcion, boolean situacion) {
       this.idCocupacional = idCocupacional;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_COCUPACIONAL", unique=true, nullable=false, length=2)
    public String getIdCocupacional() {
        return this.idCocupacional;
    }
    
    public void setIdCocupacional(String idCocupacional) {
        this.idCocupacional = idCocupacional;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


