package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContratoTrabajador generated by hbm2java
 */
@Entity
@Table(name = "CONTRATO_TRABAJADOR", schema = "dbo", catalog = "BDBRUCE")
@IdClass(value = ContratoTrabajadorId.class)
public class ContratoTrabajador implements java.io.Serializable {

    private String idTrabajador;
    private int idContrato;
    private Date fechaInicio;
    private double montoContrato;
    private Date fechaFin;
    private Date fechaCese;
    private String motivoCese;
    private String idTcontrato;
    private int idEcontrato;
    private int idTiempo;
    private String idArea;
    private String idCargo;

    public ContratoTrabajador() {
    }

    public ContratoTrabajador(String idTrabajador, int idContrato, Date fechaInicio, double montoContrato, String idTcontrato, int idEcontrato, int idTiempo) {
        this.idTrabajador = idTrabajador;
        this.idContrato = idContrato;
        this.fechaInicio = fechaInicio;
        this.montoContrato = montoContrato;
        this.idTcontrato = idTcontrato;
        this.idEcontrato = idEcontrato;
        this.idTiempo = idTiempo;
    }

    public ContratoTrabajador(String idTrabajador, int idContrato, Date fechaInicio, double montoContrato, Date fechaFin, Date fechaCese, String idTcontrato, int idEcontrato, int idTiempo, String idArea, String idCargo) {
        this.idTrabajador = idTrabajador;
        this.idContrato = idContrato;
        this.fechaInicio = fechaInicio;
        this.montoContrato = montoContrato;
        this.fechaFin = fechaFin;
        this.fechaCese = fechaCese;
        this.idTcontrato = idTcontrato;
        this.idEcontrato = idEcontrato;
        this.idTiempo = idTiempo;
        this.idArea = idArea;
        this.idCargo = idCargo;
    }

    @Id
    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Id
    @Column(name = "ID_CONTRATO", nullable = false)
    public int getIdContrato() {
        return idContrato;
    }

    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_INICIO", nullable = false, length = 10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Column(name = "MONTO_CONTRATO", nullable = false)
    public double getMontoContrato() {
        return montoContrato;
    }

    public void setMontoContrato(double montoContrato) {
        this.montoContrato = montoContrato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_FIN", length = 10)
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_CESE", length = 10)
    public Date getFechaCese() {
        return this.fechaCese;
    }

    public void setFechaCese(Date fechaCese) {
        this.fechaCese = fechaCese;
    }

    @Column(name = "MOTIVO_CESE")
    public String getMotivoCese() {
        return motivoCese;
    }

    public void setMotivoCese(String motivoCese) {
        this.motivoCese = motivoCese;
    }

    @Column(name = "ID_TCONTRATO", nullable = false, length = 2)
    public String getIdTcontrato() {
        return this.idTcontrato;
    }

    public void setIdTcontrato(String idTcontrato) {
        this.idTcontrato = idTcontrato;
    }

    @Column(name = "ID_ECONTRATO", nullable = false)
    public int getIdEcontrato() {
        return this.idEcontrato;
    }

    public void setIdEcontrato(int idEcontrato) {
        this.idEcontrato = idEcontrato;
    }

    @Column(name = "ID_TIEMPO", nullable = false)
    public int getIdTiempo() {
        return this.idTiempo;
    }

    public void setIdTiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }

    @Column(name = "ID_AREA", nullable = false)
    public String getIdArea() {
        return idArea;
    }

    public void setIdArea(String idArea) {
        this.idArea = idArea;
    }

    @Column(name = "ID_CARGO", nullable = false)
    public String getIdCargo() {
        return idCargo;
    }

    public void setIdCargo(String idCargo) {
        this.idCargo = idCargo;
    }

}
