package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContratoTrabajador generated by hbm2java
 */
@Entity
@Table(name="CONTRATO_TRABAJADOR"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class ContratoTrabajador  implements java.io.Serializable {


     private ContratoTrabajadorId id;
     private Date fechaInicio;
     private Date fechaFin;
     private Date fechaCese;
     private int idTcontrato;
     private int idEcontrato;
     private int idTiempo;

    public ContratoTrabajador() {
    }

	
    public ContratoTrabajador(ContratoTrabajadorId id, Date fechaInicio, int idTcontrato, int idEcontrato, int idTiempo) {
        this.id = id;
        this.fechaInicio = fechaInicio;
        this.idTcontrato = idTcontrato;
        this.idEcontrato = idEcontrato;
        this.idTiempo = idTiempo;
    }
    public ContratoTrabajador(ContratoTrabajadorId id, Date fechaInicio, Date fechaFin, Date fechaCese, int idTcontrato, int idEcontrato, int idTiempo) {
       this.id = id;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaCese = fechaCese;
       this.idTcontrato = idTcontrato;
       this.idEcontrato = idEcontrato;
       this.idTiempo = idTiempo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idContrato", column=@Column(name="ID_CONTRATO", nullable=false) ) } )
    public ContratoTrabajadorId getId() {
        return this.id;
    }
    
    public void setId(ContratoTrabajadorId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CESE", length=10)
    public Date getFechaCese() {
        return this.fechaCese;
    }
    
    public void setFechaCese(Date fechaCese) {
        this.fechaCese = fechaCese;
    }

    
    @Column(name="ID_TCONTRATO", nullable=false)
    public int getIdTcontrato() {
        return this.idTcontrato;
    }
    
    public void setIdTcontrato(int idTcontrato) {
        this.idTcontrato = idTcontrato;
    }

    
    @Column(name="ID_ECONTRATO", nullable=false)
    public int getIdEcontrato() {
        return this.idEcontrato;
    }
    
    public void setIdEcontrato(int idEcontrato) {
        this.idEcontrato = idEcontrato;
    }

    
    @Column(name="ID_TIEMPO", nullable=false)
    public int getIdTiempo() {
        return this.idTiempo;
    }
    
    public void setIdTiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }




}


