package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CuentaSueldo generated by hbm2java
 */
@Entity
@Table(name="CUENTA_SUELDO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class CuentaSueldo  implements java.io.Serializable {


     private String idTrabajador;
     private String nroCuenta;
     private int idEfinanciera;

    public CuentaSueldo() {
    }

    public CuentaSueldo(String idTrabajador, String nroCuenta, int idEfinanciera) {
       this.idTrabajador = idTrabajador;
       this.nroCuenta = nroCuenta;
       this.idEfinanciera = idEfinanciera;
    }
   
     @Id 

    
    @Column(name="ID_TRABAJADOR", unique=true, nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    
    @Column(name="NRO_CUENTA", nullable=false, length=25)
    public String getNroCuenta() {
        return this.nroCuenta;
    }
    
    public void setNroCuenta(String nroCuenta) {
        this.nroCuenta = nroCuenta;
    }

    
    @Column(name="ID_EFINANCIERA", nullable=false)
    public int getIdEfinanciera() {
        return this.idEfinanciera;
    }
    
    public void setIdEfinanciera(int idEfinanciera) {
        this.idEfinanciera = idEfinanciera;
    }




}


