package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CuentaSueldo generated by hbm2java
 */
@Entity
@Table(name="CUENTA_SUELDO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class CuentaSueldo  implements java.io.Serializable {


     private String idTrabajador;
     private EntidadFinanciera entidadFinanciera;
     private Trabajador trabajador;
     private String nroCuenta;

    public CuentaSueldo() {
    }

    public CuentaSueldo(EntidadFinanciera entidadFinanciera, Trabajador trabajador, String nroCuenta) {
       this.entidadFinanciera = entidadFinanciera;
       this.trabajador = trabajador;
       this.nroCuenta = nroCuenta;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="trabajador"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID_TRABAJADOR", unique=true, nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EFINANCIERA", nullable=false)
    public EntidadFinanciera getEntidadFinanciera() {
        return this.entidadFinanciera;
    }
    
    public void setEntidadFinanciera(EntidadFinanciera entidadFinanciera) {
        this.entidadFinanciera = entidadFinanciera;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="NRO_CUENTA", nullable=false, length=25)
    public String getNroCuenta() {
        return this.nroCuenta;
    }
    
    public void setNroCuenta(String nroCuenta) {
        this.nroCuenta = nroCuenta;
    }




}


