package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EntidadFinanciera generated by hbm2java
 */
@Entity
@Table(name="ENTIDAD_FINANCIERA"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class EntidadFinanciera  implements java.io.Serializable {


     private int idEfinanciera;
     private String codigo;
     private String nombre;
     private boolean situacion;

    public EntidadFinanciera() {
    }

    public EntidadFinanciera(int idEfinanciera, String codigo, String nombre, boolean situacion) {
       this.idEfinanciera = idEfinanciera;
       this.codigo = codigo;
       this.nombre = nombre;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_EFINANCIERA", unique=true, nullable=false)
    public int getIdEfinanciera() {
        return this.idEfinanciera;
    }
    
    public void setIdEfinanciera(int idEfinanciera) {
        this.idEfinanciera = idEfinanciera;
    }

    
    @Column(name="CODIGO", nullable=false, length=3)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


