package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntradaSalidaId generated by hbm2java
 */
@Embeddable
public class EntradaSalidaId  implements java.io.Serializable {


     private String idTrabajador;
     private Date hsalida;

    public EntradaSalidaId() {
    }

    public EntradaSalidaId(String idTrabajador, Date hsalida) {
       this.idTrabajador = idTrabajador;
       this.hsalida = hsalida;
    }
   


    @Column(name="ID_TRABAJADOR", nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }


    @Column(name="HSALIDA", nullable=false, length=16)
    public Date getHsalida() {
        return this.hsalida;
    }
    
    public void setHsalida(Date hsalida) {
        this.hsalida = hsalida;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntradaSalidaId) ) return false;
		 EntradaSalidaId castOther = ( EntradaSalidaId ) other; 
         
		 return ( (this.getIdTrabajador()==castOther.getIdTrabajador()) || ( this.getIdTrabajador()!=null && castOther.getIdTrabajador()!=null && this.getIdTrabajador().equals(castOther.getIdTrabajador()) ) )
 && ( (this.getHsalida()==castOther.getHsalida()) || ( this.getHsalida()!=null && castOther.getHsalida()!=null && this.getHsalida().equals(castOther.getHsalida()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTrabajador() == null ? 0 : this.getIdTrabajador().hashCode() );
         result = 37 * result + ( getHsalida() == null ? 0 : this.getHsalida().hashCode() );
         return result;
   }   


}


