package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoContrato generated by hbm2java
 */
@Entity
@Table(name="ESTADO_CONTRATO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class EstadoContrato  implements java.io.Serializable {


     private int idEcontrato;
     private String descripcion;
     private boolean situacion;

    public EstadoContrato() {
    }

    public EstadoContrato(int idEcontrato, String descripcion, boolean situacion) {
       this.idEcontrato = idEcontrato;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_ECONTRATO", unique=true, nullable=false)
    public int getIdEcontrato() {
        return this.idEcontrato;
    }
    
    public void setIdEcontrato(int idEcontrato) {
        this.idEcontrato = idEcontrato;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


