package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoTrabajador generated by hbm2java
 */
@Entity
@Table(name="ESTADO_TRABAJADOR"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class EstadoTrabajador  implements java.io.Serializable {


     private int idEtrabajador;
     private String descripcion;
     private boolean situacion;

    public EstadoTrabajador() {
    }

    public EstadoTrabajador(int idEtrabajador, String descripcion, boolean situacion) {
       this.idEtrabajador = idEtrabajador;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_ETRABAJADOR", unique=true, nullable=false)
    public int getIdEtrabajador() {
        return this.idEtrabajador;
    }
    
    public void setIdEtrabajador(int idEtrabajador) {
        this.idEtrabajador = idEtrabajador;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


