package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoContrato generated by hbm2java
 */
@Entity
@Table(name="ESTADO_CONTRATO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class EstadoContrato  implements java.io.Serializable {


     private int idEcontrato;
     private String descripcion;
     private boolean situacion;
     private Set<ContratoTrabajador> contratoTrabajadors = new HashSet<ContratoTrabajador>(0);

    public EstadoContrato() {
    }

	
    public EstadoContrato(int idEcontrato, String descripcion, boolean situacion) {
        this.idEcontrato = idEcontrato;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public EstadoContrato(int idEcontrato, String descripcion, boolean situacion, Set<ContratoTrabajador> contratoTrabajadors) {
       this.idEcontrato = idEcontrato;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.contratoTrabajadors = contratoTrabajadors;
    }
   
     @Id 

    
    @Column(name="ID_ECONTRATO", unique=true, nullable=false)
    public int getIdEcontrato() {
        return this.idEcontrato;
    }
    
    public void setIdEcontrato(int idEcontrato) {
        this.idEcontrato = idEcontrato;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoContrato")
    public Set<ContratoTrabajador> getContratoTrabajadors() {
        return this.contratoTrabajadors;
    }
    
    public void setContratoTrabajadors(Set<ContratoTrabajador> contratoTrabajadors) {
        this.contratoTrabajadors = contratoTrabajadors;
    }




}


