package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoTrabajador generated by hbm2java
 */
@Entity
@Table(name = "ESTADO_TRABAJADOR",
        schema = "dbo",
        catalog = "BDBRUCE"
)
public class EstadoTrabajador implements java.io.Serializable {

    private int idEtrabajador;
    private int codigo;
    private String descripcion;
    private Boolean situacion;
    private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public EstadoTrabajador() {
    }

    public EstadoTrabajador(int idEtrabajador, int codigo, String descripcion) {
        this.idEtrabajador = idEtrabajador;
        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public EstadoTrabajador(int idEtrabajador, int codigo, String descripcion, Boolean situacion, Set<Trabajador> trabajadors) {
        this.idEtrabajador = idEtrabajador;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.situacion = situacion;
        this.trabajadors = trabajadors;
    }

    @Id
    @Column(name = "ID_ETRABAJADOR", unique = true, nullable = false)
    public int getIdEtrabajador() {
        return this.idEtrabajador;
    }

    public void setIdEtrabajador(int idEtrabajador) {
        this.idEtrabajador = idEtrabajador;
    }

    @Column(name = "CODIGO", nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "SITUACION")
    public Boolean getSituacion() {
        return this.situacion;
    }

    public void setSituacion(Boolean situacion) {
        this.situacion = situacion;
    }

    @JsonBackReference
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoTrabajador")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }

    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }

}
