package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;

/**
 * FormacionId generated by hbm2java
 */
public class FormacionId implements java.io.Serializable {

    private String idTrabajador;
    private int idFormacion;

    public FormacionId() {
    }

    public FormacionId(String idTrabajador, int idFormacion) {
        this.idTrabajador = idTrabajador;
        this.idFormacion = idFormacion;
    }

    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Column(name = "ID_FORMACION", nullable = false)
    public int getIdFormacion() {
        return this.idFormacion;
    }

    public void setIdFormacion(int idFormacion) {
        this.idFormacion = idFormacion;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.idTrabajador);
        hash = 31 * hash + this.idFormacion;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FormacionId other = (FormacionId) obj;
        if (this.idFormacion != other.idFormacion) {
            return false;
        }
        if (!Objects.equals(this.idTrabajador, other.idTrabajador)) {
            return false;
        }
        return true;
    }

    

}
