package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Formacion generated by hbm2java
 */
@Entity
@Table(name = "FORMACION", schema = "dbo", catalog = "BDBRUCE")
@IdClass(value = FormacionId.class)
public class Formacion implements java.io.Serializable {

    private String idTrabajador;
    private int idFormacion;
    private String institucion;
    private String descripcion;
    private int idTestudio;
    private int idEestudio;

    public Formacion() {
    }

    public Formacion(String idTrabajador, int idFormacion, String institucion, String descripcion, int idTestudio, int idEestudio) {
        this.idTrabajador = idTrabajador;
        this.idFormacion = idFormacion;
        this.institucion = institucion;
        this.descripcion = descripcion;
        this.idTestudio = idTestudio;
        this.idEestudio = idEestudio;
    }

    @Id
    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Id
    @Column(name = "ID_FORMACION", nullable = false)
    public int getIdFormacion() {
        return idFormacion;
    }

    public void setIdFormacion(int idFormacion) {
        this.idFormacion = idFormacion;
    }

    @Column(name = "INSTITUCION", nullable = false, length = 25)
    public String getInstitucion() {
        return this.institucion;
    }

    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    @Column(name = "DESCRIPCION", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "ID_TESTUDIO", nullable = false)
    public int getIdTestudio() {
        return this.idTestudio;
    }

    public void setIdTestudio(int idTestudio) {
        this.idTestudio = idTestudio;
    }

    @Column(name = "ID_EESTUDIO", nullable = false)
    public int getIdEestudio() {
        return this.idEestudio;
    }

    public void setIdEestudio(int idEestudio) {
        this.idEestudio = idEestudio;
    }

}
