package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Formacion generated by hbm2java
 */
@Entity
@Table(name="FORMACION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Formacion  implements java.io.Serializable {


     private FormacionId id;
     private String institucion;
     private String descripcion;
     private int idTestudio;
     private int idEestudio;

    public Formacion() {
    }

	
    public Formacion(FormacionId id, String institucion, int idTestudio, int idEestudio) {
        this.id = id;
        this.institucion = institucion;
        this.idTestudio = idTestudio;
        this.idEestudio = idEestudio;
    }
    public Formacion(FormacionId id, String institucion, String descripcion, int idTestudio, int idEestudio) {
       this.id = id;
       this.institucion = institucion;
       this.descripcion = descripcion;
       this.idTestudio = idTestudio;
       this.idEestudio = idEestudio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idFormacion", column=@Column(name="ID_FORMACION", nullable=false) ) } )
    public FormacionId getId() {
        return this.id;
    }
    
    public void setId(FormacionId id) {
        this.id = id;
    }

    
    @Column(name="INSTITUCION", nullable=false, length=25)
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ID_TESTUDIO", nullable=false)
    public int getIdTestudio() {
        return this.idTestudio;
    }
    
    public void setIdTestudio(int idTestudio) {
        this.idTestudio = idTestudio;
    }

    
    @Column(name="ID_EESTUDIO", nullable=false)
    public int getIdEestudio() {
        return this.idEestudio;
    }
    
    public void setIdEestudio(int idEestudio) {
        this.idEestudio = idEestudio;
    }




}


