package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name="FORMA_PAGO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class FormaPago  implements java.io.Serializable {


     private int idFpago;
     private String descripcion;
     private boolean situacion;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public FormaPago() {
    }

	
    public FormaPago(int idFpago, String descripcion, boolean situacion) {
        this.idFpago = idFpago;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public FormaPago(int idFpago, String descripcion, boolean situacion, Set<Trabajador> trabajadors) {
       this.idFpago = idFpago;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.trabajadors = trabajadors;
    }
   
     @Id 

    
    @Column(name="ID_FPAGO", unique=true, nullable=false)
    public int getIdFpago() {
        return this.idFpago;
    }
    
    public void setIdFpago(int idFpago) {
        this.idFpago = idFpago;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPago")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


