package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name="FORMA_PAGO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class FormaPago  implements java.io.Serializable {


     private int idFpago;
     private String descripcion;
     private boolean situacion;

    public FormaPago() {
    }

    public FormaPago(int idFpago, String descripcion, boolean situacion) {
       this.idFpago = idFpago;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_FPAGO", unique=true, nullable=false)
    public int getIdFpago() {
        return this.idFpago;
    }
    
    public void setIdFpago(int idFpago) {
        this.idFpago = idFpago;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


