package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormacionId generated by hbm2java
 */
@Embeddable
public class FormacionId  implements java.io.Serializable {


     private String idTrabajador;
     private int idFormacion;

    public FormacionId() {
    }

    public FormacionId(String idTrabajador, int idFormacion) {
       this.idTrabajador = idTrabajador;
       this.idFormacion = idFormacion;
    }
   


    @Column(name="ID_TRABAJADOR", nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }


    @Column(name="ID_FORMACION", nullable=false)
    public int getIdFormacion() {
        return this.idFormacion;
    }
    
    public void setIdFormacion(int idFormacion) {
        this.idFormacion = idFormacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormacionId) ) return false;
		 FormacionId castOther = ( FormacionId ) other; 
         
		 return ( (this.getIdTrabajador()==castOther.getIdTrabajador()) || ( this.getIdTrabajador()!=null && castOther.getIdTrabajador()!=null && this.getIdTrabajador().equals(castOther.getIdTrabajador()) ) )
 && (this.getIdFormacion()==castOther.getIdFormacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTrabajador() == null ? 0 : this.getIdTrabajador().hashCode() );
         result = 37 * result + this.getIdFormacion();
         return result;
   }   


}


