package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formacion generated by hbm2java
 */
@Entity
@Table(name="FORMACION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Formacion  implements java.io.Serializable {


     private FormacionId id;
     private EstadoEstudio estadoEstudio;
     private TipoEstudio tipoEstudio;
     private Trabajador trabajador;
     private String institucion;
     private String descripcion;

    public Formacion() {
    }

	
    public Formacion(FormacionId id, Trabajador trabajador, String institucion) {
        this.id = id;
        this.trabajador = trabajador;
        this.institucion = institucion;
    }
    public Formacion(FormacionId id, EstadoEstudio estadoEstudio, TipoEstudio tipoEstudio, Trabajador trabajador, String institucion, String descripcion) {
       this.id = id;
       this.estadoEstudio = estadoEstudio;
       this.tipoEstudio = tipoEstudio;
       this.trabajador = trabajador;
       this.institucion = institucion;
       this.descripcion = descripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idFormacion", column=@Column(name="ID_FORMACION", nullable=false) ) } )
    public FormacionId getId() {
        return this.id;
    }
    
    public void setId(FormacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EESTUDIO")
    public EstadoEstudio getEstadoEstudio() {
        return this.estadoEstudio;
    }
    
    public void setEstadoEstudio(EstadoEstudio estadoEstudio) {
        this.estadoEstudio = estadoEstudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TESTUDIO")
    public TipoEstudio getTipoEstudio() {
        return this.tipoEstudio;
    }
    
    public void setTipoEstudio(TipoEstudio tipoEstudio) {
        this.tipoEstudio = tipoEstudio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRABAJADOR", nullable=false, insertable=false, updatable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="INSTITUCION", nullable=false, length=25)
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


