package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Funcion generated by hbm2java
 */
@Entity
@Table(name = "FUNCION", schema = "dbo", catalog = "BDBRUCE")
@IdClass(value = FuncionId.class)
public class Funcion implements java.io.Serializable {

    private String idArea;
    private int idCargo;
    private int idFuncion;
    private String nombre;
    private String detalle;
    private boolean situacion;

    public Funcion() {
    }

    public Funcion(String idArea, int idCargo, int idFuncion, String nombre, String detalle, boolean situacion) {
        this.idArea = idArea;
        this.idCargo = idCargo;
        this.idFuncion = idFuncion;
        this.nombre = nombre;
        this.detalle = detalle;
        this.situacion = situacion;
    }

    @Id
    @Column(name = "ID_AREA", nullable = false, length = 5)
    public String getIdArea() {
        return idArea;
    }

    public void setIdArea(String idArea) {
        this.idArea = idArea;
    }

    @Id
    @Column(name = "ID_CARGO", nullable = false)
    public int getIdCargo() {
        return this.idCargo;
    }

    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }

    @Id
    @Column(name = "ID_FUNCION", nullable = false)
    public int getIdFuncion() {
        return this.idFuncion;
    }

    public void setIdFuncion(int idFuncion) {
        this.idFuncion = idFuncion;
    }

    @Column(name = "NOMBRE", nullable = false, length = 70)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "DETALLE", length = 200)
    public String getDetalle() {
        return this.detalle;
    }

    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

}
