package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcion generated by hbm2java
 */
@Entity
@Table(name="FUNCION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Funcion  implements java.io.Serializable {


     private int idFuncion;
     private Date fecha;
     private String descripcion;
     private String detalle;
     private boolean situacion;
     private int idCargo;

    public Funcion() {
    }

	
    public Funcion(int idFuncion, Date fecha, boolean situacion, int idCargo) {
        this.idFuncion = idFuncion;
        this.fecha = fecha;
        this.situacion = situacion;
        this.idCargo = idCargo;
    }
    public Funcion(int idFuncion, Date fecha, String descripcion, String detalle, boolean situacion, int idCargo) {
       this.idFuncion = idFuncion;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.detalle = detalle;
       this.situacion = situacion;
       this.idCargo = idCargo;
    }
   
     @Id 

    
    @Column(name="ID_FUNCION", unique=true, nullable=false)
    public int getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(int idFuncion) {
        this.idFuncion = idFuncion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="DETALLE", length=200)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    
    @Column(name="ID_CARGO", nullable=false)
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }




}


