package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name="GENERO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Genero  implements java.io.Serializable {


     private int idGenero;
     private String descripcion;
     private boolean situacion;

    public Genero() {
    }

	
    public Genero(int idGenero, boolean situacion) {
        this.idGenero = idGenero;
        this.situacion = situacion;
    }
    public Genero(int idGenero, String descripcion, boolean situacion) {
       this.idGenero = idGenero;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_GENERO", unique=true, nullable=false)
    public int getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(int idGenero) {
        this.idGenero = idGenero;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


