package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="MENU"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Menu  implements java.io.Serializable {


     private int idMenu;
     private String icono;
     private String descripcion;
     private boolean situacion;

    public Menu() {
    }

	
    public Menu(int idMenu, boolean situacion) {
        this.idMenu = idMenu;
        this.situacion = situacion;
    }
    public Menu(int idMenu, String icono, String descripcion, boolean situacion) {
       this.idMenu = idMenu;
       this.icono = icono;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_MENU", unique=true, nullable=false)
    public int getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(int idMenu) {
        this.idMenu = idMenu;
    }

    
    @Column(name="ICONO", length=25)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


