package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "MENU", schema = "dbo", catalog = "BDBRUCE")
public class Menu implements java.io.Serializable {

    private String idMenu;
    private String iconCls;
    private String text;
    private String handler;
    private boolean leaf;
    private String idSupmenu;

    public Menu() {
    }

    public Menu(String idMenu, String iconCls, String text, String handler, String idSupmenu) {
        this.idMenu = idMenu;
        this.iconCls = iconCls;
        this.text = text;
        this.handler = handler;
        this.idSupmenu = idSupmenu;
    }

    @Id
    @Column(name = "ID_MENU", nullable = false)
    public String getIdMenu() {
        return idMenu;
    }

    public void setIdMenu(String idMenu) {
        this.idMenu = idMenu;
    }

    @Column(name = "ICON_CLS", nullable = false)
    public String getIconCls() {
        return iconCls;
    }

    public void setIconCls(String iconCls) {
        this.iconCls = iconCls;
    }

    @Column(name = "DESCRIPCION", nullable = false)
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "ACCION", nullable = false)
    public String getHandler() {
        return handler;
    }

    public void setHandler(String handler) {
        this.handler = handler;
    }

    @Column(name = "LEAF", nullable = false)
    public boolean isLeaf() {
        return leaf;
    }

    public void setLeaf(boolean leaf) {
        this.leaf = leaf;
    }

    @Column(name = "ID_SUPMENU", nullable = false)
    public String getIdSupmenu() {
        return idSupmenu;
    }

    public void setIdSupmenu(String idSupmenu) {
        this.idSupmenu = idSupmenu;
    }
    
}
