package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nacionalidad generated by hbm2java
 */
@Entity
@Table(name = "NACIONALIDAD",
         schema = "dbo",
         catalog = "BDBRUCE"
)
public class Nacionalidad implements java.io.Serializable {

    private int idNacionalidad;
    private Long codigo;
    private String descripcion;
    private boolean situacion;
    private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public Nacionalidad() {
    }

    public Nacionalidad(int idNacionalidad, String descripcion, boolean situacion) {
        this.idNacionalidad = idNacionalidad;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }

    public Nacionalidad(int idNacionalidad, Long codigo, String descripcion, boolean situacion, Set<Trabajador> trabajadors) {
        this.idNacionalidad = idNacionalidad;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.situacion = situacion;
        this.trabajadors = trabajadors;
    }

    @Id

    @Column(name = "ID_NACIONALIDAD", unique = true, nullable = false)
    public int getIdNacionalidad() {
        return this.idNacionalidad;
    }

    public void setIdNacionalidad(int idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }

    @Column(name = "CODIGO")
    public Long getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 25)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    @JsonBackReference
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "nacionalidad")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }

    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }

}
