package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name="PERMISO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Permiso  implements java.io.Serializable {


     private PermisoId id;
     private TipoPermiso tipoPermiso;
     private Trabajador trabajador;
     private Date fechaRetorno;

    public Permiso() {
    }

    public Permiso(PermisoId id, TipoPermiso tipoPermiso, Trabajador trabajador, Date fechaRetorno) {
       this.id = id;
       this.tipoPermiso = tipoPermiso;
       this.trabajador = trabajador;
       this.fechaRetorno = fechaRetorno;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="fechaSalida", column=@Column(name="FECHA_SALIDA", nullable=false, length=10) ) } )
    public PermisoId getId() {
        return this.id;
    }
    
    public void setId(PermisoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TPERMISO", nullable=false)
    public TipoPermiso getTipoPermiso() {
        return this.tipoPermiso;
    }
    
    public void setTipoPermiso(TipoPermiso tipoPermiso) {
        this.tipoPermiso = tipoPermiso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRABAJADOR", nullable=false, insertable=false, updatable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_RETORNO", nullable=false, length=10)
    public Date getFechaRetorno() {
        return this.fechaRetorno;
    }
    
    public void setFechaRetorno(Date fechaRetorno) {
        this.fechaRetorno = fechaRetorno;
    }




}


