package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermisoId generated by hbm2java
 */
@Embeddable
public class PermisoId  implements java.io.Serializable {


     private String idTrabajador;
     private Date fechaSalida;

    public PermisoId() {
    }

    public PermisoId(String idTrabajador, Date fechaSalida) {
       this.idTrabajador = idTrabajador;
       this.fechaSalida = fechaSalida;
    }
   


    @Column(name="ID_TRABAJADOR", nullable=false, length=15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }


    @Column(name="FECHA_SALIDA", nullable=false, length=10)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisoId) ) return false;
		 PermisoId castOther = ( PermisoId ) other; 
         
		 return ( (this.getIdTrabajador()==castOther.getIdTrabajador()) || ( this.getIdTrabajador()!=null && castOther.getIdTrabajador()!=null && this.getIdTrabajador().equals(castOther.getIdTrabajador()) ) )
 && ( (this.getFechaSalida()==castOther.getFechaSalida()) || ( this.getFechaSalida()!=null && castOther.getFechaSalida()!=null && this.getFechaSalida().equals(castOther.getFechaSalida()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTrabajador() == null ? 0 : this.getIdTrabajador().hashCode() );
         result = 37 * result + ( getFechaSalida() == null ? 0 : this.getFechaSalida().hashCode() );
         return result;
   }   


}


