package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegimenPensionario generated by hbm2java
 */
@Entity
@Table(name = "REGIMEN_PENSIONARIO",
         schema = "dbo",
         catalog = "BDBRUCE"
)
public class RegimenPensionario implements java.io.Serializable {

    private String idRpensionario;
    private String descripcion;
    private boolean cuspp;
    private boolean situacion;

    public RegimenPensionario() {
    }

    public RegimenPensionario(String idRpensionario, boolean cuspp, boolean situacion) {
        this.idRpensionario = idRpensionario;
        this.cuspp = cuspp;
        this.situacion = situacion;
    }

    public RegimenPensionario(String idRpensionario, String descripcion, boolean cuspp, boolean situacion) {
        this.idRpensionario = idRpensionario;
        this.descripcion = descripcion;
        this.cuspp = cuspp;
        this.situacion = situacion;
    }

    @Id
    @Column(name = "ID_RPENSIONARIO", unique = true, nullable = false, length = 2)
    public String getIdRpensionario() {
        return this.idRpensionario;
    }

    public void setIdRpensionario(String idRpensionario) {
        this.idRpensionario = idRpensionario;
    }

    @Column(name = "DESCRIPCION", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "CUSPP", nullable = false)
    public boolean isCuspp() {
        return this.cuspp;
    }

    public void setCuspp(boolean cuspp) {
        this.cuspp = cuspp;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

}
