package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegimenPensionario generated by hbm2java
 */
@Entity
@Table(name="REGIMEN_PENSIONARIO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class RegimenPensionario  implements java.io.Serializable {


     private int idRpensionario;
     private String codigo;
     private String descripcion;
     private boolean cuspp;
     private boolean situacion;

    public RegimenPensionario() {
    }

	
    public RegimenPensionario(int idRpensionario, String codigo, boolean cuspp, boolean situacion) {
        this.idRpensionario = idRpensionario;
        this.codigo = codigo;
        this.cuspp = cuspp;
        this.situacion = situacion;
    }
    public RegimenPensionario(int idRpensionario, String codigo, String descripcion, boolean cuspp, boolean situacion) {
       this.idRpensionario = idRpensionario;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.cuspp = cuspp;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_RPENSIONARIO", unique=true, nullable=false)
    public int getIdRpensionario() {
        return this.idRpensionario;
    }
    
    public void setIdRpensionario(int idRpensionario) {
        this.idRpensionario = idRpensionario;
    }

    
    @Column(name="CODIGO", nullable=false, length=3)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CUSPP", nullable=false)
    public boolean isCuspp() {
        return this.cuspp;
    }
    
    public void setCuspp(boolean cuspp) {
        this.cuspp = cuspp;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


