package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Remuneracion generated by hbm2java
 */
@Entity
@Table(name="REMUNERACION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Remuneracion  implements java.io.Serializable {


     private RemuneracionId id;
     private Date fecha;
     private BigDecimal monto;

    public Remuneracion() {
    }

    public Remuneracion(RemuneracionId id, Date fecha, BigDecimal monto) {
       this.id = id;
       this.fecha = fecha;
       this.monto = monto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idContrato", column=@Column(name="ID_CONTRATO", nullable=false) ), 
        @AttributeOverride(name="idRemuneracion", column=@Column(name="ID_REMUNERACION", nullable=false) ) } )
    public RemuneracionId getId() {
        return this.id;
    }
    
    public void setId(RemuneracionId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="MONTO", nullable=false, precision=13, scale=4)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


