package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Submenu generated by hbm2java
 */
@Entity
@Table(name="SUBMENU"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Submenu  implements java.io.Serializable {


     private int idSubmenu;
     private String link;
     private String descripcion;
     private boolean situacion;
     private int idMenu;

    public Submenu() {
    }

    public Submenu(int idSubmenu, String link, String descripcion, boolean situacion, int idMenu) {
       this.idSubmenu = idSubmenu;
       this.link = link;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.idMenu = idMenu;
    }
   
     @Id 

    
    @Column(name="ID_SUBMENU", unique=true, nullable=false)
    public int getIdSubmenu() {
        return this.idSubmenu;
    }
    
    public void setIdSubmenu(int idSubmenu) {
        this.idSubmenu = idSubmenu;
    }

    
    @Column(name="LINK", nullable=false, length=30)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

    
    @Column(name="ID_MENU", nullable=false)
    public int getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(int idMenu) {
        this.idMenu = idMenu;
    }




}


