package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="SUCURSAL"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Sucursal  implements java.io.Serializable {


     private String idSucursal;
     private Empresa empresa;
     private String direccion;
     private boolean situacion;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public Sucursal() {
    }

	
    public Sucursal(String idSucursal, Empresa empresa, String direccion, boolean situacion) {
        this.idSucursal = idSucursal;
        this.empresa = empresa;
        this.direccion = direccion;
        this.situacion = situacion;
    }
    public Sucursal(String idSucursal, Empresa empresa, String direccion, boolean situacion, Set<Trabajador> trabajadors) {
       this.idSucursal = idSucursal;
       this.empresa = empresa;
       this.direccion = direccion;
       this.situacion = situacion;
       this.trabajadors = trabajadors;
    }
   
     @Id 

    
    @Column(name="ID_SUCURSAL", unique=true, nullable=false, length=2)
    public String getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(String idSucursal) {
        this.idSucursal = idSucursal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EMPRESA", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="DIRECCION", nullable=false, length=80)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


