package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;

/**
 * TextralaboralId generated by hbm2java
 */
public class TextralaboralId implements java.io.Serializable {

    private String idTrabajador;
    private String idTextralaboral;

    public TextralaboralId() {
    }

    public TextralaboralId(String idTrabajador, String idTextralaboral) {
        this.idTrabajador = idTrabajador;
        this.idTextralaboral = idTextralaboral;
    }

    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return this.idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Column(name = "ID_TEXTRALABORAL", nullable = false, length = 10)
    public String getIdTextralaboral() {
        return idTextralaboral;
    }

    public void setIdTextralaboral(String idTextralaboral) {
        this.idTextralaboral = idTextralaboral;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + Objects.hashCode(this.idTrabajador);
        hash = 37 * hash + Objects.hashCode(this.idTextralaboral);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TextralaboralId other = (TextralaboralId) obj;
        if (!Objects.equals(this.idTrabajador, other.idTrabajador)) {
            return false;
        }
        if (!Objects.equals(this.idTextralaboral, other.idTextralaboral)) {
            return false;
        }
        return true;
    }
}
