package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Textralaboral generated by hbm2java
 */
@Entity
@IdClass(value = TextralaboralId.class)
@Table(name = "TEXTRALABORAL", schema = "dbo", catalog = "BDBRUCE")
public class Textralaboral implements java.io.Serializable {

    private String idTrabajador;
    private String idTextralaboral;
    private Date fecha;
    private String horaInicio;
    private String horaSalida;
    private String descripcion;
    private int idActividad;
    private int idTtextra;

    private String trabajador;

    public Textralaboral() {
    }

    public Textralaboral(String idTrabajador, Date fecha, String horaInicio, String horaSalida, String descripcion, int idActividad, int idTtextra) {
        this.idTrabajador = idTrabajador;
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.horaSalida = horaSalida;
        this.descripcion = descripcion;
        this.idActividad = idActividad;
        this.idTtextra = idTtextra;
    }

    @Id
    @Column(name = "ID_TRABAJADOR", nullable = false)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Id
    @Column(name = "ID_TEXTRALABORAL", nullable = false, length = 10)
    public String getIdTextralaboral() {
        return idTextralaboral;
    }

    public void setIdTextralaboral(String idTextralaboral) {
        this.idTextralaboral = idTextralaboral;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA", nullable = false)
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "HORA_INICIO", nullable = false)
    public String getHoraInicio() {
        return horaInicio;
    }

    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Column(name = "HORA_SALIDA", nullable = false)
    public String getHoraSalida() {
        return horaSalida;
    }

    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }

    @Column(name = "DESCRIPCION")
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "ID_ACTIVIDAD", nullable = false)
    public int getIdActividad() {
        return idActividad;
    }

    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }

    @Column(name = "ID_TTEXTRA", nullable = false)
    public int getIdTtextra() {
        return idTtextra;
    }

    public void setIdTtextra(int idTtextra) {
        this.idTtextra = idTtextra;
    }

    @Generated(GenerationTime.NEVER)
    @Column(name = "TRABAJADOR", insertable = false, updatable = false)
    public String getTrabajador() {
        return trabajador;
    }

    public void setTrabajador(String trabajador) {
        this.trabajador = trabajador;
    }
}
