package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Textralaboral generated by hbm2java
 */
@Entity
@Table(name="TEXTRALABORAL"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Textralaboral  implements java.io.Serializable {


     private TextralaboralId id;
     private Date horaInicio;
     private Date horaSalida;
     private String op;
     private String actividad;
     private int idTtextra;

    public Textralaboral() {
    }

    public Textralaboral(TextralaboralId id, Date horaInicio, Date horaSalida, String op, String actividad, int idTtextra) {
       this.id = id;
       this.horaInicio = horaInicio;
       this.horaSalida = horaSalida;
       this.op = op;
       this.actividad = actividad;
       this.idTtextra = idTtextra;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="fecha", column=@Column(name="FECHA", nullable=false, length=10) ) } )
    public TextralaboralId getId() {
        return this.id;
    }
    
    public void setId(TextralaboralId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_INICIO", nullable=false, length=16)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_SALIDA", nullable=false, length=16)
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }

    
    @Column(name="OP", nullable=false, length=25)
    public String getOp() {
        return this.op;
    }
    
    public void setOp(String op) {
        this.op = op;
    }

    
    @Column(name="ACTIVIDAD", nullable=false, length=100)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="ID_TTEXTRA", nullable=false)
    public int getIdTtextra() {
        return this.idTtextra;
    }
    
    public void setIdTtextra(int idTtextra) {
        this.idTtextra = idTtextra;
    }




}


