package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiempoContrato generated by hbm2java
 */
@Entity
@Table(name="TIEMPO_CONTRATO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TiempoContrato  implements java.io.Serializable {


     private int idTiempo;
     private int nroMeses;
     private String descripcion;
     private boolean situacion;
     private Set<ContratoTrabajador> contratoTrabajadors = new HashSet<ContratoTrabajador>(0);

    public TiempoContrato() {
    }

	
    public TiempoContrato(int idTiempo, int nroMeses, String descripcion, boolean situacion) {
        this.idTiempo = idTiempo;
        this.nroMeses = nroMeses;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public TiempoContrato(int idTiempo, int nroMeses, String descripcion, boolean situacion, Set<ContratoTrabajador> contratoTrabajadors) {
       this.idTiempo = idTiempo;
       this.nroMeses = nroMeses;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.contratoTrabajadors = contratoTrabajadors;
    }
   
     @Id 

    
    @Column(name="ID_TIEMPO", unique=true, nullable=false)
    public int getIdTiempo() {
        return this.idTiempo;
    }
    
    public void setIdTiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }

    
    @Column(name="NRO_MESES", nullable=false)
    public int getNroMeses() {
        return this.nroMeses;
    }
    
    public void setNroMeses(int nroMeses) {
        this.nroMeses = nroMeses;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiempoContrato")
    public Set<ContratoTrabajador> getContratoTrabajadors() {
        return this.contratoTrabajadors;
    }
    
    public void setContratoTrabajadors(Set<ContratoTrabajador> contratoTrabajadors) {
        this.contratoTrabajadors = contratoTrabajadors;
    }




}


