package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name="TIPO_DOCUMENTO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoDocumento  implements java.io.Serializable {


     private int idTdocumento;
     private String codigo;
     private String descripcion;
     private boolean situacion;

    public TipoDocumento() {
    }

	
    public TipoDocumento(int idTdocumento, boolean situacion) {
        this.idTdocumento = idTdocumento;
        this.situacion = situacion;
    }
    public TipoDocumento(int idTdocumento, String codigo, String descripcion, boolean situacion) {
       this.idTdocumento = idTdocumento;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_TDOCUMENTO", unique=true, nullable=false)
    public int getIdTdocumento() {
        return this.idTdocumento;
    }
    
    public void setIdTdocumento(int idTdocumento) {
        this.idTdocumento = idTdocumento;
    }

    
    @Column(name="CODIGO", length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


