package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name="TIPO_CONTRATO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoContrato  implements java.io.Serializable {


     private int idTcontrato;
     private String codigo;
     private String tipo;
     private boolean situacion;

    public TipoContrato() {
    }

    public TipoContrato(int idTcontrato, String codigo, String tipo, boolean situacion) {
       this.idTcontrato = idTcontrato;
       this.codigo = codigo;
       this.tipo = tipo;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_TCONTRATO", unique=true, nullable=false)
    public int getIdTcontrato() {
        return this.idTcontrato;
    }
    
    public void setIdTcontrato(int idTcontrato) {
        this.idTcontrato = idTcontrato;
    }

    
    @Column(name="CODIGO", nullable=false, length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="TIPO", nullable=false, length=25)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


