package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEstudio generated by hbm2java
 */
@Entity
@Table(name="TIPO_ESTUDIO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoEstudio  implements java.io.Serializable {


     private int idTestudio;
     private String descripcion;
     private boolean situacion;
     private Set<Formacion> formacions = new HashSet<Formacion>(0);

    public TipoEstudio() {
    }

	
    public TipoEstudio(int idTestudio, String descripcion, boolean situacion) {
        this.idTestudio = idTestudio;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public TipoEstudio(int idTestudio, String descripcion, boolean situacion, Set<Formacion> formacions) {
       this.idTestudio = idTestudio;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.formacions = formacions;
    }
   
     @Id 

    
    @Column(name="ID_TESTUDIO", unique=true, nullable=false)
    public int getIdTestudio() {
        return this.idTestudio;
    }
    
    public void setIdTestudio(int idTestudio) {
        this.idTestudio = idTestudio;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEstudio")
    public Set<Formacion> getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set<Formacion> formacions) {
        this.formacions = formacions;
    }




}


