package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoTextra generated by hbm2java
 */
@Entity
@Table(name="TIPO_TEXTRA"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoTextra  implements java.io.Serializable {


     private int idTtextra;
     private String descripcion;
     private boolean situacion;

    public TipoTextra() {
    }

    public TipoTextra(int idTtextra, String descripcion, boolean situacion) {
       this.idTtextra = idTtextra;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_TTEXTRA", unique=true, nullable=false)
    public int getIdTtextra() {
        return this.idTtextra;
    }
    
    public void setIdTtextra(int idTtextra) {
        this.idTtextra = idTtextra;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


