package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEs generated by hbm2java
 */
@Entity
@Table(name="TIPO_ES"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoEs  implements java.io.Serializable {


     private int idTes;
     private String tipo;
     private boolean situacion;
     private Set<EntradaSalida> entradaSalidas = new HashSet<EntradaSalida>(0);

    public TipoEs() {
    }

	
    public TipoEs(int idTes, String tipo, boolean situacion) {
        this.idTes = idTes;
        this.tipo = tipo;
        this.situacion = situacion;
    }
    public TipoEs(int idTes, String tipo, boolean situacion, Set<EntradaSalida> entradaSalidas) {
       this.idTes = idTes;
       this.tipo = tipo;
       this.situacion = situacion;
       this.entradaSalidas = entradaSalidas;
    }
   
     @Id 

    
    @Column(name="ID_TES", unique=true, nullable=false)
    public int getIdTes() {
        return this.idTes;
    }
    
    public void setIdTes(int idTes) {
        this.idTes = idTes;
    }

    
    @Column(name="TIPO", nullable=false, length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEs")
    public Set<EntradaSalida> getEntradaSalidas() {
        return this.entradaSalidas;
    }
    
    public void setEntradaSalidas(Set<EntradaSalida> entradaSalidas) {
        this.entradaSalidas = entradaSalidas;
    }




}


