package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name="TIPO_CONTRATO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoContrato  implements java.io.Serializable {


     private int idTcontrato;
     private String codigo;
     private String tipo;
     private boolean situacion;
     private Set<ContratoTrabajador> contratoTrabajadors = new HashSet<ContratoTrabajador>(0);

    public TipoContrato() {
    }

	
    public TipoContrato(int idTcontrato, String codigo, String tipo, boolean situacion) {
        this.idTcontrato = idTcontrato;
        this.codigo = codigo;
        this.tipo = tipo;
        this.situacion = situacion;
    }
    public TipoContrato(int idTcontrato, String codigo, String tipo, boolean situacion, Set<ContratoTrabajador> contratoTrabajadors) {
       this.idTcontrato = idTcontrato;
       this.codigo = codigo;
       this.tipo = tipo;
       this.situacion = situacion;
       this.contratoTrabajadors = contratoTrabajadors;
    }
   
     @Id 

    
    @Column(name="ID_TCONTRATO", unique=true, nullable=false)
    public int getIdTcontrato() {
        return this.idTcontrato;
    }
    
    public void setIdTcontrato(int idTcontrato) {
        this.idTcontrato = idTcontrato;
    }

    
    @Column(name="CODIGO", nullable=false, length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="TIPO", nullable=false, length=25)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoContrato")
    public Set<ContratoTrabajador> getContratoTrabajadors() {
        return this.contratoTrabajadors;
    }
    
    public void setContratoTrabajadors(Set<ContratoTrabajador> contratoTrabajadors) {
        this.contratoTrabajadors = contratoTrabajadors;
    }




}


