package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CONTRATO",
         schema = "dbo",
         catalog = "BDBRUCE"
)
public class TipoContrato implements java.io.Serializable {

    private String idTcontrato;
    private String descripcion;
    private boolean situacion;

    public TipoContrato() {
    }

    public TipoContrato(String idTcontrato, String descripcion, boolean situacion) {
        this.idTcontrato = idTcontrato;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }

    @Id
    @Column(name = "ID_TCONTRATO", unique = true, nullable = false, length = 2)
    public String getIdTcontrato() {
        return this.idTcontrato;
    }

    public void setIdTcontrato(String idTcontrato) {
        this.idTcontrato = idTcontrato;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 25)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

}
