package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoEstudio generated by hbm2java
 */
@Entity
@Table(name="TIPO_ESTUDIO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoEstudio  implements java.io.Serializable {


     private int idTestudio;
     private String descripcion;
     private boolean situacion;

    public TipoEstudio() {
    }

    public TipoEstudio(int idTestudio, String descripcion, boolean situacion) {
       this.idTestudio = idTestudio;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_TESTUDIO", unique=true, nullable=false)
    public int getIdTestudio() {
        return this.idTestudio;
    }
    
    public void setIdTestudio(int idTestudio) {
        this.idTestudio = idTestudio;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


