package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTrabajador generated by hbm2java
 */
@Entity
@Table(name="TIPO_TRABAJADOR"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoTrabajador  implements java.io.Serializable {


     private int idTtrabajador;
     private String codigo;
     private String descripcion;
     private boolean situacion;
     private Set<Periodo> periodos = new HashSet<Periodo>(0);
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public TipoTrabajador() {
    }

	
    public TipoTrabajador(int idTtrabajador, String codigo, String descripcion, boolean situacion) {
        this.idTtrabajador = idTtrabajador;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public TipoTrabajador(int idTtrabajador, String codigo, String descripcion, boolean situacion, Set<Periodo> periodos, Set<Trabajador> trabajadors) {
       this.idTtrabajador = idTtrabajador;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.periodos = periodos;
       this.trabajadors = trabajadors;
    }
   
     @Id 

    
    @Column(name="ID_TTRABAJADOR", unique=true, nullable=false)
    public int getIdTtrabajador() {
        return this.idTtrabajador;
    }
    
    public void setIdTtrabajador(int idTtrabajador) {
        this.idTtrabajador = idTtrabajador;
    }

    
    @Column(name="CODIGO", nullable=false, length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoTrabajador")
    public Set<Periodo> getPeriodos() {
        return this.periodos;
    }
    
    public void setPeriodos(Set<Periodo> periodos) {
        this.periodos = periodos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoTrabajador")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


