package com.bruce.dao.to;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPeriodo generated by hbm2java
 */
@Entity
@Table(name="TIPO_PERIODO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoPeriodo  implements java.io.Serializable {


     private int idTperiodo;
     private String descripcion;
     private boolean situacion;
     private Set<Periodo> periodos = new HashSet<Periodo>(0);

    public TipoPeriodo() {
    }

	
    public TipoPeriodo(int idTperiodo, String descripcion, boolean situacion) {
        this.idTperiodo = idTperiodo;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public TipoPeriodo(int idTperiodo, String descripcion, boolean situacion, Set<Periodo> periodos) {
       this.idTperiodo = idTperiodo;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.periodos = periodos;
    }
   
     @Id 

    
    @Column(name="ID_TPERIODO", unique=true, nullable=false)
    public int getIdTperiodo() {
        return this.idTperiodo;
    }
    
    public void setIdTperiodo(int idTperiodo) {
        this.idTperiodo = idTperiodo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPeriodo")
    public Set<Periodo> getPeriodos() {
        return this.periodos;
    }
    
    public void setPeriodos(Set<Periodo> periodos) {
        this.periodos = periodos;
    }




}


