package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoTrabajador generated by hbm2java
 */
@Entity
@Table(name = "TIPO_TRABAJADOR", schema = "dbo", catalog = "BDBRUCE")
public class TipoTrabajador implements java.io.Serializable {

    private int idTtrabajador;
    private String descripcion;
    private boolean hasctacts;
    private boolean hasrpensionario;
    private float pension;
    private float essalud;
    private float vida;
    private boolean jornalDiario;
    private boolean situacion;

    public TipoTrabajador() {
    }

    public TipoTrabajador(int idTtrabajador, String descripcion, boolean situacion) {
        this.idTtrabajador = idTtrabajador;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }

    @Id
    @Column(name = "ID_TTRABAJADOR", unique = true, nullable = false)
    public int getIdTtrabajador() {
        return this.idTtrabajador;
    }

    public void setIdTtrabajador(int idTtrabajador) {
        this.idTtrabajador = idTtrabajador;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "HASCTACTS", nullable = false)
    public boolean isHasctacts() {
        return hasctacts;
    }

    public void setHasctacts(boolean hasctacts) {
        this.hasctacts = hasctacts;
    }

    @Column(name = "HASRPENSIONARIO", nullable = false)
    public boolean isHasrpensionario() {
        return hasrpensionario;
    }

    public void setHasrpensionario(boolean hasrpensionario) {
        this.hasrpensionario = hasrpensionario;
    }

    @Column(name = "PENSION", nullable = false)
    public float getPension() {
        return pension;
    }

    public void setPension(float pension) {
        this.pension = pension;
    }

    @Column(name = "ESSALUD", nullable = false)
    public float getEssalud() {
        return essalud;
    }

    public void setEssalud(float essalud) {
        this.essalud = essalud;
    }

    @Column(name = "VIDA", nullable = false)
    public float getVida() {
        return vida;
    }

    public void setVida(float vida) {
        this.vida = vida;
    }

    @Column(name = "JORNAL_DIARIO", nullable = false)
    public boolean isJornalDiario() {
        return jornalDiario;
    }

    public void setJornalDiario(boolean jornalDiario) {
        this.jornalDiario = jornalDiario;
    }

    @Column(name = "SITUACION", nullable = false)
    public boolean isSituacion() {
        return this.situacion;
    }

    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

}
