package com.bruce.dao.to;
// Generated 07/09/2018 11:57:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoTrabajador generated by hbm2java
 */
@Entity
@Table(name="TIPO_TRABAJADOR"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoTrabajador  implements java.io.Serializable {


     private int idTtrabajador;
     private String codigo;
     private String descripcion;
     private boolean situacion;

    public TipoTrabajador() {
    }

    public TipoTrabajador(int idTtrabajador, String codigo, String descripcion, boolean situacion) {
       this.idTtrabajador = idTtrabajador;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_TTRABAJADOR", unique=true, nullable=false)
    public int getIdTtrabajador() {
        return this.idTtrabajador;
    }
    
    public void setIdTtrabajador(int idTtrabajador) {
        this.idTtrabajador = idTtrabajador;
    }

    
    @Column(name="CODIGO", nullable=false, length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


