package com.bruce.dao.to;
// Generated 27/06/2018 10:09:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name="TIPO_DOCUMENTO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoDocumento  implements java.io.Serializable {


     private int idTdocumento;
     private String codigo;
     private String descripcion;
     private Boolean situacion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(int idTdocumento) {
        this.idTdocumento = idTdocumento;
    }
    public TipoDocumento(int idTdocumento, String codigo, String descripcion, Boolean situacion, Set<Persona> personas) {
       this.idTdocumento = idTdocumento;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="ID_TDOCUMENTO", unique=true, nullable=false)
    public int getIdTdocumento() {
        return this.idTdocumento;
    }
    
    public void setIdTdocumento(int idTdocumento) {
        this.idTdocumento = idTdocumento;
    }

    
    @Column(name="CODIGO", length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DESCRIPCION", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION")
    public Boolean getSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(Boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoDocumento")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


