package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.ColumnTransformer;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO",
         schema = "dbo",
         catalog = "BDBRUCE"
)
public class Usuario implements java.io.Serializable {

    private String idUsuario;
    private String usu;
    private byte[] clave;
    private boolean estado;
    private boolean acceder;

    public Usuario() {
    }

    public Usuario(String idUsuario, String usu, byte[] clave, boolean estado, boolean acceder) {
        this.idUsuario = idUsuario;
        this.usu = usu;
        this.clave = clave;
        this.estado = estado;
        this.acceder = acceder;
    }
    
    private String deClave;

    @Id
    @Column(name = "ID_USUARIO", unique = true, nullable = false, length = 15)
    public String getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "USU", nullable = false, length = 12)
    public String getUsu() {
        return this.usu;
    }

    public void setUsu(String usu) {
        this.usu = usu;
    }

    @Column(name = "CLAVE", nullable = false)
    @ColumnTransformer(read = "DECRYPTBYPASSPHRASE('Bruces@22',CLAVE)", write = "ENCRYPTBYPASSPHRASE('Bruces@22',?)")
    public byte[] getClave() {
        return this.clave;
    }

    public void setClave(byte[] clave) {
        this.clave = clave;
    }
    
    @Transient
    public String getDeClave() {
        return new String(clave);
    }

    public void setDeClave(String deClave) {
        this.clave = deClave.getBytes();
        this.deClave = deClave;
    }

    @Column(name = "ESTADO", nullable = false)
    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    @Column(name = "ACCEDER", nullable = false)
    public boolean isAcceder() {
        return this.acceder;
    }

    public void setAcceder(boolean acceder) {
        this.acceder = acceder;
    }

}
