package com.bruce.dao.to;
// Generated 06/09/2018 09:02:17 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacacion generated by hbm2java
 */
@Entity
@Table(name="VACACION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Vacacion  implements java.io.Serializable {


     private VacacionId id;
     private Date fechaBase;
     private Date fechaLimite;
     private Date fechaSalida;
     private Date fechaRetorno;
     private Date fechaIngreso;
     private Integer diasUsados;
     private Integer diasComprados;

    public Vacacion() {
    }

	
    public Vacacion(VacacionId id, Date fechaBase, Date fechaLimite, Date fechaSalida, Date fechaRetorno) {
        this.id = id;
        this.fechaBase = fechaBase;
        this.fechaLimite = fechaLimite;
        this.fechaSalida = fechaSalida;
        this.fechaRetorno = fechaRetorno;
    }
    public Vacacion(VacacionId id, Date fechaBase, Date fechaLimite, Date fechaSalida, Date fechaRetorno, Date fechaIngreso, Integer diasUsados, Integer diasComprados) {
       this.id = id;
       this.fechaBase = fechaBase;
       this.fechaLimite = fechaLimite;
       this.fechaSalida = fechaSalida;
       this.fechaRetorno = fechaRetorno;
       this.fechaIngreso = fechaIngreso;
       this.diasUsados = diasUsados;
       this.diasComprados = diasComprados;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idPeriodo", column=@Column(name="ID_PERIODO", nullable=false) ) } )
    public VacacionId getId() {
        return this.id;
    }
    
    public void setId(VacacionId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BASE", nullable=false, length=10)
    public Date getFechaBase() {
        return this.fechaBase;
    }
    
    public void setFechaBase(Date fechaBase) {
        this.fechaBase = fechaBase;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_LIMITE", nullable=false, length=10)
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_SALIDA", nullable=false, length=10)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_RETORNO", nullable=false, length=10)
    public Date getFechaRetorno() {
        return this.fechaRetorno;
    }
    
    public void setFechaRetorno(Date fechaRetorno) {
        this.fechaRetorno = fechaRetorno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INGRESO", length=10)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="DIAS_USADOS")
    public Integer getDiasUsados() {
        return this.diasUsados;
    }
    
    public void setDiasUsados(Integer diasUsados) {
        this.diasUsados = diasUsados;
    }

    
    @Column(name="DIAS_COMPRADOS")
    public Integer getDiasComprados() {
        return this.diasComprados;
    }
    
    public void setDiasComprados(Integer diasComprados) {
        this.diasComprados = diasComprados;
    }




}


