package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Vacacion generated by hbm2java
 */
@Entity
@Table(name = "VACACION", schema = "dbo", catalog = "BDBRUCE")
@IdClass(value = VacacionId.class)
public class Vacacion implements java.io.Serializable {

    private String idTrabajador;
    private String idVacacion;
    private Date fechaBase;
    private Date fechaSalida;
    private Date fechaRetorno;
    private Integer diasTomados;
    private int idTVacacion;
    private int idPVacacion;

    private String tipo;

    public Vacacion() {
    }

    public Vacacion(String idTrabajador, int idPVacacion, Date fechaBase, Date fechaSalida, Date fechaRetorno, Integer diasTomados, int idTVacacion) {
        this.idTrabajador = idTrabajador;
        this.idPVacacion = idPVacacion;
        this.fechaBase = fechaBase;
        this.fechaSalida = fechaSalida;
        this.fechaRetorno = fechaRetorno;
        this.diasTomados = diasTomados;
        this.idTVacacion = idTVacacion;
    }

    @Id
    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    @Id
    @Column(name = "ID_VACACION", nullable = false)
    public String getIdVacacion() {
        return idVacacion;
    }

    public void setIdVacacion(String idVacacion) {
        this.idVacacion = idVacacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_BASE", nullable = false, length = 10)
    public Date getFechaBase() {
        return fechaBase;
    }

    public void setFechaBase(Date fechaBase) {
        this.fechaBase = fechaBase;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_SALIDA", nullable = false, length = 10)
    public Date getFechaSalida() {
        return fechaSalida;
    }

    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_RETORNO", nullable = false, length = 10)
    public Date getFechaRetorno() {
        return fechaRetorno;
    }

    public void setFechaRetorno(Date fechaRetorno) {
        this.fechaRetorno = fechaRetorno;
    }

    @Column(name = "DIAS_TOMADOS", nullable = false)
    public Integer getDiasTomados() {
        return diasTomados;
    }

    public void setDiasTomados(Integer diasTomados) {
        this.diasTomados = diasTomados;
    }

    @Column(name = "ID_TVACACION", nullable = false)
    public int getIdTVacacion() {
        return idTVacacion;
    }

    public void setIdTVacacion(int idTVacacion) {
        this.idTVacacion = idTVacacion;
    }

    @Column(name = "ID_PVACACION", nullable = false)
    public int getIdPVacacion() {
        return idPVacacion;
    }

    public void setIdPVacacion(int idPVacacion) {
        this.idPVacacion = idPVacacion;
    }

    @Generated(GenerationTime.NEVER)
    @Column(name = "TIPO", insertable = false, updatable = false)
    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

}
