package com.bruce.dao.to;
// Generated 09/09/2018 05:31:05 AM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;

/**
 * VacacionId generated by hbm2java
 */
public class VacacionId implements java.io.Serializable {

    private String idTrabajador;
    private String idVacacion;

    public VacacionId() {
    }

    public VacacionId(String idTrabajador, String idVacacion) {
        this.idTrabajador = idTrabajador;
        this.idVacacion = idVacacion;
    }

    @Column(name = "ID_TRABAJADOR", nullable = false, length = 15)
    public String getIdTrabajador() {
        return idTrabajador;
    }

    public void setIdTrabajador(String idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    
    @Column(name="ID_VACACION", nullable = false)
    public String getIdVacacion() {
        return idVacacion;
    }

    public void setIdVacacion(String idVacacion) {
        this.idVacacion = idVacacion;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.idTrabajador);
        hash = 97 * hash + Objects.hashCode(this.idVacacion);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final VacacionId other = (VacacionId) obj;
        if (!Objects.equals(this.idTrabajador, other.idTrabajador)) {
            return false;
        }
        if (!Objects.equals(this.idVacacion, other.idVacacion)) {
            return false;
        }
        return true;
    }

}
