package dao.dto.hibernate;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Afiliacion generated by hbm2java
 */
@Entity
@Table(name="AFILIACION"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Afiliacion  implements java.io.Serializable {


     private AfiliacionId id;
     private RegimenPensionario regimenPensionario;
     private Trabajador trabajador;
     private String observacion;
     private String nrocuspp;

    public Afiliacion() {
    }

	
    public Afiliacion(AfiliacionId id, RegimenPensionario regimenPensionario, Trabajador trabajador) {
        this.id = id;
        this.regimenPensionario = regimenPensionario;
        this.trabajador = trabajador;
    }
    public Afiliacion(AfiliacionId id, RegimenPensionario regimenPensionario, Trabajador trabajador, String observacion, String nrocuspp) {
       this.id = id;
       this.regimenPensionario = regimenPensionario;
       this.trabajador = trabajador;
       this.observacion = observacion;
       this.nrocuspp = nrocuspp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="idRpensionario", column=@Column(name="ID_RPENSIONARIO", nullable=false) ) } )
    public AfiliacionId getId() {
        return this.id;
    }
    
    public void setId(AfiliacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_RPENSIONARIO", nullable=false, insertable=false, updatable=false)
    public RegimenPensionario getRegimenPensionario() {
        return this.regimenPensionario;
    }
    
    public void setRegimenPensionario(RegimenPensionario regimenPensionario) {
        this.regimenPensionario = regimenPensionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRABAJADOR", nullable=false, insertable=false, updatable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    
    @Column(name="OBSERVACION", length=50)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="NROCUSPP", length=25)
    public String getNrocuspp() {
        return this.nrocuspp;
    }
    
    public void setNrocuspp(String nrocuspp) {
        this.nrocuspp = nrocuspp;
    }




}


