package dao.dto.hibernate;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="EMPRESA"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Empresa  implements java.io.Serializable {


     private String idEmpresa;
     private String descripcion;
     private boolean situacion;
     private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);

    public Empresa() {
    }

	
    public Empresa(String idEmpresa, String descripcion, boolean situacion) {
        this.idEmpresa = idEmpresa;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public Empresa(String idEmpresa, String descripcion, boolean situacion, Set<Sucursal> sucursals) {
       this.idEmpresa = idEmpresa;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.sucursals = sucursals;
    }
   
     @Id 

    
    @Column(name="ID_EMPRESA", unique=true, nullable=false, length=2)
    public String getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(String idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Sucursal> getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set<Sucursal> sucursals) {
        this.sucursals = sucursals;
    }




}


