package dao.dto.hibernate;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Submenu generated by hbm2java
 */
@Entity
@Table(name="SUBMENU"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Submenu  implements java.io.Serializable {


     private int idSubmenu;
     private Menu menu;
     private String link;
     private String descripcion;
     private boolean situacion;

    public Submenu() {
    }

    public Submenu(int idSubmenu, Menu menu, String link, String descripcion, boolean situacion) {
       this.idSubmenu = idSubmenu;
       this.menu = menu;
       this.link = link;
       this.descripcion = descripcion;
       this.situacion = situacion;
    }
   
     @Id 

    
    @Column(name="ID_SUBMENU", unique=true, nullable=false)
    public int getIdSubmenu() {
        return this.idSubmenu;
    }
    
    public void setIdSubmenu(int idSubmenu) {
        this.idSubmenu = idSubmenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MENU", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    
    @Column(name="LINK", nullable=false, length=30)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=30)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }




}


