package dao.dto.hibernate;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Textralaboral generated by hbm2java
 */
@Entity
@Table(name="TEXTRALABORAL"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class Textralaboral  implements java.io.Serializable {


     private TextralaboralId id;
     private TipoTextra tipoTextra;
     private Trabajador trabajador;
     private Date horaInicio;
     private Date horaSalida;
     private String op;
     private String actividad;

    public Textralaboral() {
    }

    public Textralaboral(TextralaboralId id, TipoTextra tipoTextra, Trabajador trabajador, Date horaInicio, Date horaSalida, String op, String actividad) {
       this.id = id;
       this.tipoTextra = tipoTextra;
       this.trabajador = trabajador;
       this.horaInicio = horaInicio;
       this.horaSalida = horaSalida;
       this.op = op;
       this.actividad = actividad;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTrabajador", column=@Column(name="ID_TRABAJADOR", nullable=false, length=15) ), 
        @AttributeOverride(name="fecha", column=@Column(name="FECHA", nullable=false, length=10) ) } )
    public TextralaboralId getId() {
        return this.id;
    }
    
    public void setId(TextralaboralId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TTEXTRA", nullable=false)
    public TipoTextra getTipoTextra() {
        return this.tipoTextra;
    }
    
    public void setTipoTextra(TipoTextra tipoTextra) {
        this.tipoTextra = tipoTextra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TRABAJADOR", nullable=false, insertable=false, updatable=false)
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_INICIO", nullable=false, length=16)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_SALIDA", nullable=false, length=16)
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }

    
    @Column(name="OP", nullable=false, length=25)
    public String getOp() {
        return this.op;
    }
    
    public void setOp(String op) {
        this.op = op;
    }

    
    @Column(name="ACTIVIDAD", nullable=false, length=100)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }




}


