package dao.dto.hibernate;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPermiso generated by hbm2java
 */
@Entity
@Table(name="TIPO_PERMISO"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoPermiso  implements java.io.Serializable {


     private int idTpermiso;
     private String tipo;
     private boolean situacion;
     private Set<Permiso> permisos = new HashSet<Permiso>(0);

    public TipoPermiso() {
    }

	
    public TipoPermiso(int idTpermiso, String tipo, boolean situacion) {
        this.idTpermiso = idTpermiso;
        this.tipo = tipo;
        this.situacion = situacion;
    }
    public TipoPermiso(int idTpermiso, String tipo, boolean situacion, Set<Permiso> permisos) {
       this.idTpermiso = idTpermiso;
       this.tipo = tipo;
       this.situacion = situacion;
       this.permisos = permisos;
    }
   
     @Id 

    
    @Column(name="ID_TPERMISO", unique=true, nullable=false)
    public int getIdTpermiso() {
        return this.idTpermiso;
    }
    
    public void setIdTpermiso(int idTpermiso) {
        this.idTpermiso = idTpermiso;
    }

    
    @Column(name="TIPO", nullable=false, length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPermiso")
    public Set<Permiso> getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set<Permiso> permisos) {
        this.permisos = permisos;
    }




}


