package dao.dto.hibernate;
// Generated 17/06/2018 01:48:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTextra generated by hbm2java
 */
@Entity
@Table(name="TIPO_TEXTRA"
    ,schema="dbo"
    ,catalog="BDBRUCE"
)
public class TipoTextra  implements java.io.Serializable {


     private int idTtextra;
     private String descripcion;
     private boolean situacion;
     private Set<Textralaboral> textralaborals = new HashSet<Textralaboral>(0);

    public TipoTextra() {
    }

	
    public TipoTextra(int idTtextra, String descripcion, boolean situacion) {
        this.idTtextra = idTtextra;
        this.descripcion = descripcion;
        this.situacion = situacion;
    }
    public TipoTextra(int idTtextra, String descripcion, boolean situacion, Set<Textralaboral> textralaborals) {
       this.idTtextra = idTtextra;
       this.descripcion = descripcion;
       this.situacion = situacion;
       this.textralaborals = textralaborals;
    }
   
     @Id 

    
    @Column(name="ID_TTEXTRA", unique=true, nullable=false)
    public int getIdTtextra() {
        return this.idTtextra;
    }
    
    public void setIdTtextra(int idTtextra) {
        this.idTtextra = idTtextra;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SITUACION", nullable=false)
    public boolean isSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(boolean situacion) {
        this.situacion = situacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoTextra")
    public Set<Textralaboral> getTextralaborals() {
        return this.textralaborals;
    }
    
    public void setTextralaborals(Set<Textralaboral> textralaborals) {
        this.textralaborals = textralaborals;
    }




}


